"""
    AI DISCLAIMER:
    This code was generated by an AI language model (ChatGPT) through multiple prompts and iterations.
    The AI generated code was modified by a human developer to fit the specific requirements of this demo application.
"""

import streamlit as st
import requests
import pandas as pd
import plotly.express as px

API_URL = "http://127.0.0.1:8000/name-stats-full"

st.set_page_config(page_title="Name Comparison", layout="wide")

# 🔹 Title
st.markdown("<h1 style='text-align:center;'>Name Comparison Dashboard</h1>", unsafe_allow_html=True)

# 🔹 Input Section
col1, col2 = st.columns(2)

with col1:
    name1 = st.text_input("Name 1", value="Michael")
    sex1 = st.selectbox("Sex 1", ["", "M", "F"])

with col2:
    name2 = st.text_input("Name 2", value="Bethany")
    sex2 = st.selectbox("Sex 2", ["", "M", "F"])


# 🔹 API Call Helper
def fetch_name_data(name, sex):
    params = {"name": name}
    if sex:
        params["sex"] = sex

    try:
        r = requests.get(API_URL, params=params)
        r.raise_for_status()
        return r.json()
    except Exception as e:
        st.error(f"API error: {e}")
        return None


data1 = fetch_name_data(name1, sex1)
data2 = fetch_name_data(name2, sex2)

st.divider()

# 🔹 Card UI helper
def render_card(data):
    if not data:
        st.error("No data found")
        return

    st.markdown(f"""
        <div style="
            background-color:#ffffff;
            padding:20px;
            border-radius:12px;
            margin-bottom:15px;
            border:1px solid #e6e6e6;
            box-shadow:0 2px 6px rgba(0,0,0,0.05);
        ">
            <h3 style="margin-bottom:10px;">{data['name']} ({data['sex']})</h3>
            <p><b>Estimated Age:</b> {data['estimated_age']:.2f}</p>
            <p><b>Most Likely Age:</b> {data['most_likely_age']}</p>
            <p><b>Total Count:</b> {data['total_occurrence_count']}</p>
            <p><b>Estimated Alive:</b> {data['estimated_alive_count']:.0f}</p>
            <p><b>Rank (Gendered):</b> {data['all_time_rank_gendered']}</p>
        </div>
    """, unsafe_allow_html=True)


# 🔹 Cards side-by-side
col1, col2 = st.columns(2)

with col1:
    render_card(data1)

with col2:
    render_card(data2)

st.divider()

# 🔹 Line Charts (Occurrences vs Alive)
col1, col2 = st.columns(2)

def render_line_chart(data):
    if not data:
        return

    occ = data["occurrence_by_year"]
    alive = data["alive_occurrence_by_year"]

    df = pd.DataFrame({
        "Year": list(occ.keys()),
        "Occurrences": list(occ.values()),
        "Alive": list(alive.values())
    }).sort_values("Year")

    fig = px.line(df, x="Year", y=["Occurrences", "Alive"],
                  title=f"{data['name']} Trends")

    st.plotly_chart(fig, width="stretch")


with col1:
    render_line_chart(data1)

with col2:
    render_line_chart(data2)

st.divider()

# 🔹 Combined Comparison Chart
if data1 and data2:
    df_compare = pd.DataFrame({
        "Count Comparison": ["Total Occurrences", "Estimated Alive"],
        data1["name"]: [
            data1["total_occurrence_count"],
            data1["estimated_alive_count"]
        ],
        data2["name"]: [
            data2["total_occurrence_count"],
            data2["estimated_alive_count"]
        ]
    })

    df_melt = df_compare.melt(id_vars="Count Comparison",
                             var_name="Metric",
                             value_name="Value")

    fig = px.bar(df_melt, x="Count Comparison", y="Value", color="Metric",
                 barmode="group",
                 title="Overall Comparison")

    st.plotly_chart(fig, width="stretch")